# An Application for Lottery Addiction

We've been tasked to help contribute to the development of a mobile app that is meant to help lottery addicts better estimate their chances of winning.

Many people start playing the lottery for fun, but for some this activity turns into a habit which eventually escalates into addiction. Like other compulsive gamblers, lottery addicts soon begin spending from their savings and loans, they start to accumulate debts, and eventually engage in desperate behaviors like theft.

A medical institute that aims to prevent and treat gambling addictions wants to build a dedicated mobile app to help lottery addicts better estimate their chances of winning. The institute has a team of engineers that will build the app, but they need us to create the logical core of the app and calculate probabilities.

For the first version of the app, they want us to focus on the 6/49 lottery and build functions that enable users to answer questions like:

- What is the probability of winning the big prize with a single ticket?
- What is the probability of winning the big prize if we play 40 different tickets (or any other number)?
- What is the probability of having at least five (or four, or three, or two) winning numbers on a single ticket?

The institute also wants us to consider historical data coming from the national 6/49 lottery game in Canada. The data set has data for 3,665 drawings, dating from 1982 to 2018.

Our goal here is to enable users to answer probability questions about playing the lottery.



## The Core Functions

We plan on using a couple of equations pretty often if calculating the odds of drawing a set of numbers at random. The first equation will deal with calculating factorials, and the second will deal with calculating combinations.

\begin{equation}
n! = n \times (n - 1) \times (n - 2) \times ... \times 2 \times 1
\end{equation}

In [1]:
#function calculates factorials
def factorial(n):
    fact = 1
    for i in range(n, 0, -1):
        fact*=i
    return fact

\begin{equation}
_nC_k = {n \choose k} =  \frac{n!}{k!(n-k)!}
\end{equation}

In [2]:
#fucntion that calculates combinations
def combinations(n,k):
    numerator = factorial(n)
    denomenator = factorial(k)*(factorial(n-k))
    return numerator/denomenator

## One-ticket Probability

Now that we've developed the two core functions we will repeatedly utilize moving forward, it's time to we focus on writing a function that calculates the probability of winning the "big prize".

To quickly summarize the mechanics of the 6/49 lottery...
- Six numbers are drawn from a set of 49 numbers that range from 1 to 49
- A player wins the "big prize" if all of their six numbers match those drawn
- If a single number does not match, the player doesn't win the "big prize"

For the first version of this app, we're looking to empower would-be players by helping calculate the probability of winning the big prize with various number they play on a single ticket.

We'll start building the function that calculates the probability of winning the big prize for any given ticket.

In [3]:
# function takes in a list of six unique numbers and prints the probability of winning
def one_ticket_probability(list_numbers):
    possible_outcomes = combinations(49,6)
    probability = 1/possible_outcomes
    print("The likelylihood that {0} will result in a winning ticket is about {1:.10%}. Or, in other words, you have 1 chance out of {2:,} of winning the big prize."
          .format(str(list_numbers),probability*100, int(possible_outcomes)))

In [4]:
one_ticket_probability([1,2,3,4,5,6])

The likelylihood that [1, 2, 3, 4, 5, 6] will result in a winning ticket is about 0.0007151124%. Or, in other words, you have 1 chance out of 13,983,816 of winning the big prize.


It should be easy to see that the combination of unique numbers doesn't effect the likelihood of winning.

But would be interesting is helping the user forcast what they *could* have won if using the same set of numbers in a previous drawing.

## Historical Data Check for Canada Lottery

With access to the historical dataset of the Canada Lottery available to us, we can help the user better realize the odds of them winning past lottery drawings.

The Canada 6/49 lottery dataset we plan on exploring houses historical data for 3,665 past drawings dating back from 1982 to 2018.

Let's explore the dataset a bit.

In [5]:
import pandas as pd
lottery = pd.read_csv('649.csv')

In [6]:
lottery.head()

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
0      649            1                0  6/12/1982               3   
1      649            2                0  6/19/1982               8   
2      649            3                0  6/26/1982               1   
3      649            4                0   7/3/1982               3   
4      649            5                0  7/10/1982               5   

   NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
0              11              12              14              41   
1              33              36              37              39   
2               6              23              24              27   
3               9              10              13              20   
4              14              21              31              34   

   NUMBER DRAWN 6  BONUS NUMBER  
0              43            13  
1              41             9  
2              39            34  
3              43            34  
4              47            45

In [7]:
lottery.tail()

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
3660      649         3587                0   6/6/2018              10   
3661      649         3588                0   6/9/2018              19   
3662      649         3589                0  6/13/2018               6   
3663      649         3590                0  6/16/2018               2   
3664      649         3591                0  6/20/2018              14   

      NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
3660              15              23              38              40   
3661              25              31              36              46   
3662              22              24              31              32   
3663              15              21              31              38   
3664              24              31              35              37   

      NUMBER DRAWN 6  BONUS NUMBER  
3660              41            35  
3661              47            26  
3662              34            16  
3663              49             8  
3664              48            17

In [8]:
lottery.shape

(3665, 11)

In [9]:
lottery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 11 columns):
PRODUCT            3665 non-null int64
DRAW NUMBER        3665 non-null int64
SEQUENCE NUMBER    3665 non-null int64
DRAW DATE          3665 non-null object
NUMBER DRAWN 1     3665 non-null int64
NUMBER DRAWN 2     3665 non-null int64
NUMBER DRAWN 3     3665 non-null int64
NUMBER DRAWN 4     3665 non-null int64
NUMBER DRAWN 5     3665 non-null int64
NUMBER DRAWN 6     3665 non-null int64
BONUS NUMBER       3665 non-null int64
dtypes: int64(10), object(1)
memory usage: 315.0+ KB


It looks like the dataset is clean with no non-null entries to account for. 

There's a total of 3,665 rows with 11 columns.

`PRODUCT` seems to correspond with the name of the drawing itself, the "649" lottery.

It isn't at all clear what the `SEQUENCE NUMBER` entries entail seeing that they are all just zeros. 

The `DRAWN DATE` is self-explanatory. And the bonus number is mechanism utilized in other similar lottery number drawing games that increases the payout if the player happens to hit all the other numbers. 

The columns we're most interested are

1. NUMBER DRAWN 1
2. NUMBER DRAWN 2
3. NUMBER DRAWN 3
4. NUMBER DRAWN 4
5. NUMBER DRAWN 5
6. NUMBER DRAWN 6

With these six columns in mind, we'll be able to let users compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.

The engineering team behind the development of this app has told us that we need to be aware of the following details:

- Inside the app, the user inputs six different numbers from 1 to 49.
- Under the hood, the six numbers will come as a Python list and serve as an input to our function.
- The engineering team wants us to write a function that prints:
    - the number of times the combination selected occurred in the Canada data set; and
    - the probability of winning the big prize in the next drawing with that combination.

In [10]:
# function takes in row of lottery dataframe as input and returns a set containing the six winning numbers
def extract_numbers(row):
    row = row[4:10]
    winning_numbers = set(row)
    return winning_numbers

In [11]:
winning_numbers = lottery.apply(extract_numbers, axis=1)

In [12]:
winning_numbers.head(10)

0     {3, 41, 11, 12, 43, 14}
1     {33, 36, 37, 39, 8, 41}
2      {1, 6, 39, 23, 24, 27}
3      {3, 9, 10, 43, 13, 20}
4     {34, 5, 14, 47, 21, 31}
5     {8, 41, 20, 21, 25, 31}
6    {33, 36, 42, 18, 25, 28}
7     {7, 40, 16, 17, 48, 31}
8     {5, 38, 37, 10, 23, 27}
9     {4, 37, 46, 15, 48, 30}
dtype: object

In [13]:
#function takes two inputs, a list containing user numbers and pandas Series containing sets with the winning numbers
def check_historical_occurence(user_nums_list, winning_nums_set):
    user_nums_set = set(user_nums_list)
    occurence_check = winning_nums_set == user_nums_set
    num_occurences = occurence_check.sum()
    
    if num_occurences == 0:
        print(
        '''
        The combination {} has never occured in past drawings.
        The chances of this combination being drawn is is about 0.00072%. 
        In other words, you'll likely win once within 13,983,816 attempts.
        '''.format(user_nums_list))
        
    else:
        print(
        '''
        The combination {} has occured {} time(s) is past drawings.
        The chances of this combination being drawn again is about 0.00072%.
        In other words, you'll likely win once within 13,983,816 attempts.
        '''.format(user_nums_list, num_occurences)
        )

In [14]:
#testing losing numbers
user_inputs = [1,2,3,4,5,6]
thing = check_historical_occurence(user_inputs, winning_numbers)


        The combination [1, 2, 3, 4, 5, 6] has never occured in past drawings.
        The chances of this combination being drawn is is about 0.00072%. 
        In other words, you'll likely win once within 13,983,816 attempts.
        


In [15]:
#testing winning numbers
user_inputs = [33, 36, 37, 39, 8, 41]
thing = check_historical_occurence(user_inputs, winning_numbers)


        The combination [33, 36, 37, 39, 8, 41] has occured 1 time(s) is past drawings.
        The chances of this combination being drawn again is about 0.00072%.
        In other words, you'll likely win once within 13,983,816 attempts.
        


To summarize the results, regardless of whether the user's current selection of numbers hit in the past or not, the odds of winning remain the same.

There's still only a 0.00072% chance of winning the big prize. In essence, past perfomance is not indicative of future success.

## Multi-ticket Probability

There are those who play the lottery often that feel as though buying multiple tickets at once will increase their chances of winning any given drawing.

We will move forward with designing a function that takes into account the number of tickets a user plans to buy and presents what the odds are of winning the big prize.

The engineering team has the following notes for development of this feature:

- The user will input the number of different tickets they want to play
    - Without inputting the specific combinations they intend to play
- The function is expected to see an integer between 1 and 13,983,816 (the maximum number of different tickets).
- The function should print information about the probability of winning the big prize depending on the number of different tickets played.

Let's begin writing the function.

In [20]:
#function takes input from user on multiple tickets
def multi_ticket_probability(num_tickets):
    num_combinations = combinations(49,6)
    probability = num_tickets/num_combinations
    percentage = probability * 100
    
    if num_tickets == 1:
        print('''Your chances to win the big prize with one ticket are {:.6f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(percentage, int(num_combinations)))
    
    else:
        combinations_simplified = round(num_combinations / num_tickets)   
        print('''Your chances to win the big prize with {:,} different tickets are {:.6f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(num_tickets, percentage,
                                                               combinations_simplified))

In [21]:
test_inputs = [1, 10, 100, 10000, 1000000, 6991908, 13983816]

for test_input in test_inputs:
    multi_ticket_probability(test_input)
    print('------------------------') # output delimiter

Your chances to win the big prize with one ticket are 0.000007%.
In other words, you have a 1 in 13,983,816 chances to win.
------------------------
Your chances to win the big prize with 10 different tickets are 0.000072%.
In other words, you have a 1 in 1,398,382 chances to win.
------------------------
Your chances to win the big prize with 100 different tickets are 0.000715%.
In other words, you have a 1 in 139,838 chances to win.
------------------------
Your chances to win the big prize with 10,000 different tickets are 0.071511%.
In other words, you have a 1 in 1,398 chances to win.
------------------------
Your chances to win the big prize with 1,000,000 different tickets are 7.151124%.
In other words, you have a 1 in 14 chances to win.
------------------------
Your chances to win the big prize with 6,991,908 different tickets are 50.000000%.
In other words, you have a 1 in 2 chances to win.
------------------------
Your chances to win the big prize with 13,983,816 different ti

Above, we can see the range of odds of winning the big prize from one ticket to 13,983,816 tickets.

But what if the user also wanted to see probabilities for getting a certain fraction of the numbers correctly. Many of these kinds of lotteries not only have a big prize for getting *all* of the numbers in the drawing, but they also give out prizes for those who get two, three, four, or five of the winning numbers. 

In this respect, the engineering team has given the following notes:

- Inside the app, the user inputs:
    - six different numbers from 1 to 49; and
    - an integer between 2 and 5 that represents the number of winning numbers expected
- Our function prints information about the probability of having the inputted number of winning numbers.





In [47]:
#function takes in an integer between 2 and 5 and prints chances of winning
def probability_less_6(nums):
    num_combinations = combinations(6, nums)
    num_combinations_remaining = combinations(43, 6-nums)
    successful_outcomes = num_combinations * num_combinations_remaining

    
    total_combinations = combinations(49,6)  
    probability = successful_outcomes/total_combinations 
    
    percentage = probability * 100
    combinations_simplified = round(total_combinations/successful_outcomes)

    print( 
'''
Your chances of getting exactly {} out of the 6 winning numbers are {:.4f}%.
Or, in other words, your chances of gettting exactly {} out of the 6 winning numbers is 1 in {:,}.
'''.format(nums,percentage,nums,combinations_simplified))

In [48]:
#testing outputs for 2,3,4,5
possible_inputs = [2,3,4,5]

for i in [2,3,4,5]:
    probability_less_6(i)
    print('-'*20)


Your chances of getting exactly 2 out of the 6 winning numbers are 13.2378%.
Or, in other words, your chances of gettting exactly 2 out of the 6 winning numbers is 1 in 8.

--------------------

Your chances of getting exactly 3 out of the 6 winning numbers are 1.7650%.
Or, in other words, your chances of gettting exactly 3 out of the 6 winning numbers is 1 in 57.

--------------------

Your chances of getting exactly 4 out of the 6 winning numbers are 0.0969%.
Or, in other words, your chances of gettting exactly 4 out of the 6 winning numbers is 1 in 1,032.

--------------------

Your chances of getting exactly 5 out of the 6 winning numbers are 0.0018%.
Or, in other words, your chances of gettting exactly 5 out of the 6 winning numbers is 1 in 54,201.

--------------------


# Conclusion

We've developed a few functions for our app that will help the user realize the odds of winning the lottery.

- `one_ticket_probability()` — calculates the probability of winning the big prize with a single ticket
- `check_historical_occurrence()` — checks whether a certain combination has occurred in the Canada lottery data set
- `multi_ticket_probability()` — calculates the probability for any number of of tickets between 1 and 13,983,816
- `probability_less_6()` — calculates the probability of having two, three, four or five winning numbers

## Next Steps
There are a few next steps in store for this project worth considering.

- Coupling the odds of winning with funny and strange phenomenon
    - Example: 100 times more likely to get struck by lightning than win the big prize
- Condesning certain functions (`one_ticket_probability()`, `check_historical_occurrence()`)
- Expanding the `probability_less_6()` function to include the chances of having *at least* two, three, four, or five winning numbers
    - Internal Note:
    - The number of successful outcomes for having at least four winning numbers is the sum of these three numbers:
        - The number of successful outcomes for having four winning numbers exactly
        - The number of successful outcomes for having five winning numbers exactly
        - The number of successful outcomes for having six winning numbers exactly